"""empty message

Revision ID: 246c5f40857f
Revises: f6e753643f99
Create Date: 2017-04-16 17:51:32.276803

"""

# revision identifiers, used by Alembic.
revision = '246c5f40857f'
down_revision = 'f6e753643f99'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    ### end Alembic commands ###
