"""empty message

Revision ID: 27f90a2be264
Revises: 246c5f40857f
Create Date: 2017-04-17 12:32:05.840899

"""

# revision identifiers, used by Alembic.
revision = '27f90a2be264'
down_revision = '246c5f40857f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('view', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'view')
    ### end Alembic commands ###
